{% set name = "quantlab" %}
{% set version = "0.2.0" %}
{% set sha256 = "153c15686b92a68570d4c997d3bd40ac13d775803fdac72232696393409de05d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - quantlab_launcher >=0.1.1
    - notebook >=4.2

test:
  imports:
    - quantlab

about:
  home: https://github.com/quantlabio/quantlab
  license: BSD 3-Clause
  license_file: LICENSE
  summary: A pre-alpha version of a computational environment for quant
  description: |
    quantlab is a computational environment for quant, forked from Jupyter Lab,
    focuses on quantitative finance.
  doc_url: https://doc.quantlab.io/
  dev_url: https://github.com/quantlabio/quantlab

extra:
  recipe-maintainers:
    - lab4quant
