{% set name = "quantlab" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 48e918a0ab7d912575317db4680c842a344f996ed9a6150b6cfad0afe8d0eea6

build:
  number: 1
  noarch: python
  script: pip install . -vvv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - quantlab_launcher >=0.1.1
    - notebook >=4.2

test:
  imports:
    - quantlab

about:
  home: https://github.com/quantlabio/quantlab
  license: BSD 3-Clause
  license_file: LICENSE
  summary: A pre-alpha version of a computational environment for quant
  description: |
    quantlab is a computational environment for quant, forked from Jupyter Lab,
    focuses on quantitative finance.
  doc_url: https://doc.quantlab.io/
  dev_url: https://github.com/quantlabio/quantlab

extra:
  recipe-maintainers:
    - lab4quant
