travis:
  secure:
    BINSTAR_TOKEN: vJoqypacXrJ6o5Gwhs4rqpUmVqpf+bi8CS6e2t5IPqSkxOk3erimZha9H4T0mr8tBrYA/LBm+F8R+4IR05JlRyLqIzM0NH8xpn6/PhGk5+0D3raYEjvehbugQWqLyBGyfNFY8Z77NNSCtEo8OJkhkE3UqmGIBbf4N44+wGHR/OnCffLKnIL86A3b3UJqBZHmX6EPjZ2O/bXFBi4SI0Jy9iHdWsVKqHKb7c/fqjhZSjr06X1auU/txW99oT6GdzRkuiY5vtU81NiS1dDHE7PW50Rnk0luQYbOqeMOjOFsI6Lntqw6FGwehTH/1CObMgPXRoA3thXI2mqFvwnstvhlT6NrDQpDOsQnea03RR7c+5O5L5ltii6lrpPCbJWoMcvRzFTq1bILeoiXvSiDw6AkNo4nCqzqVe0LTwv4DuSoPntndFpwrk18S5x2sQrOeeKJmbirgb/nD1bO/KFJ0tgEkV9qt0+y0q1JrK0Iy3sSoqVqib825eEIC67Q2nm9sl1IrwsWVzuyWCSTUyxLkw8SSJc1mimYUq2FnMSlUR5hAzXRQYywnreefDi90uE3o1wHjd5jfwRAHVpelZHMr5zPe6tZQG6lTB177gnLr5tjUA1Hqk3DLPiUCkO2EVmE4GR1l4qcAVSDN9vyD86HHbFS18n2B38PPDYxwQ3eKkuGKkI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
