travis:
  secure:
    BINSTAR_TOKEN: sbq6T0WXWrusrNEHC1J180MTm8wfHFECfrGBAg8nCllXwWLBL5ZKgjriugieZM541yIwsOR4siQjy3cR4dKq6XBo3p1UsrDU0JZSa6/3+wUZ1p71jiqS8MsI78L0suGZ4hy/Gz+4ozkCKAl8AQAUBEB0rR1vF1UqwdSquTuLsE49zAJIkXhqki86rADy2hsligs1YxZ8dfvPZc20NvCfPsLgDdd0u7x2dFnaAXc78d2NAOepUkmlddlwDhXhk9cPHBZ30XSkRKKbCWjNfbBA+xGKpqFLhZWKjIyXtFDEGifQucK1E/oQNGSn8kR3ykRM3H3YsKb6c5Auxp9WiNn6bIYFAJfgtmdoFn140/6ek3v0KksyNJp0/kss+b7Q/ltm7N6xc6B7VGjzhjcP0P8L6N84quNYucpBd+1XepE8+cUi9RvtT5+XjDXypikVuMz4JdrOvqBVRNqOo9jKMzEjxnRWreOpGrIXTqBKitsHqCwGsHUnALus5rjGGOf/uzFTrDBKgPKUVGkI78XILIanxCn2VxS/H3kwwrrFXAjDfU0JaJGgMukGD0dk37OLyJ173+3VUDu8BsP7aDgSKz/radts9L4SYO8fek4t/ciB+qeDyybtknPuZhXH/JqUKJfivTrronqx8gC84Z6gsqpxQclf/HOE5PCxlta2ZkRZZsg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
